

const faqData = {
    section1: [
        {
            id:0,
            Q: "What is a Solar PV system?",
            A:"A photovoltaic (PV) system is composed of one or more solar panels combined with an inverter that uses energy from the Sun to generate electricity.",
        },
        {
            id:1,
            Q:"What is the life of a Solar PV system? ",
            A:"The average life of Solar PV system lies between 20-30 years. After this time period they don’t cease to produce electricity however as they age their ability to work efficiently slows down."
        },
        {
            id:2,
            Q:"Do solar panels work on cloudy days?",
            A:"Solar panels do work on cloudy days, however not as efficiently on sunny days. The sunlight however penetrates through clouds as well thus negating the myth of solar panels not working on cloudy days. Though estimates range, solar panels will generate about 10 – 25% of their normal power output on a cloudy day. ",

        },
        {
            id:3,
            Q:"What are the types of Solar PV systems available in the market? ",
            A:"There are three types of PV systems available:On-Grid – This system is directly connected to your main electricity supply. The number of units generated by the smart tree are adjusted in your electricity bill.Off-Grid- Connected to the household supply, an off-grid system has batteries to work as backup during a power cut.Hybrid-  With the best of both worlds (off-grid and the on-grid) hybrid provides batteries during a power cut while being connected to the grid.",
        },
       
        {
            id:4,
            Q:"Why should you choose solar over normal?",
            A:"It is imperative that we understand what the need of the hour is, with the unprecedented turn of events we are left with no choice but to choose sustainability. The choice of natural over “normal” will not only help us combat the ongoing climate crisis however would prove beneficial to the buyer for it helps the buyer save money. Another advantage is that the production of this greener form of energy will use the renewable natural resource prevalent in abundance and help save the extensively used non-renewable fossil fuels."
        },
        {
            id:5,
            Q:"How is a rooftop significant to the installation process? ",
            A:"Generally rooftop area required for a 1 Kw system is 100 sq ft however our smart solar tree requires only 4 sq ft and due to advanced mechanism and technology the prerequisite of drilling into the roof is no longer valid thereby  maintaining the structural integrity of your roof.",
        },
        {
            id:6,
            Q:"What does a break-even period mean in the world of solar energy?",
            A:"Break-even period is the period till which your solar has generated enough money that it covers your total investment cost. Generally, the break-even period is from 3-5 years.For example:Investment =  ₹50,000 Savings per Year =  ₹10000 Then break even period is 5 years.",
        },
        {
            id:7,
            Q:"What is net-metering?",
            A:"It is a meter that is attached to your main electrical meter which counts the number of units generated by solar system and used by the household. If the units generated are excessive, they go back to the grid.Your electricity bill on the contrary is the difference between units consumed and units generated.For example, your PV system generates 150 units per month. While your consumption was 200 units.Then you will be charged only for the 200-150= 50 units consumed. thus your electrcity bill:Previous: 200*4 =  ₹800 New: 50*4= ₹200 (if  ₹4 is the rate per kWh in your city)",
        },
        {
            id:8,
            Q:"Does the government offer subsidies for investing in solar energy?",
            A:"Yes. The Government of India offers various subsidies however the Centre and State vary in their offers for the same. Thus subsidies vary from location to location and depend on total Kw of system for the on-grid solar system. For off-grid system there is no subsidy available. To know more about subsidies in your location, contact our customer care.",
        },
        {
            id:9,
            Q:"How reliable is solar energy?",
            A:"The reliability of the solar energy can be easily judged by the warranty of its different parts; the panels have a warranty of approximately 25 years and the inverter with that of 5-10 years. The maintenance cost of a solar system is near to negligible. Therefore, effectively it has a zero* running cost. In a country like India we approximately have more than 300 sunny days making it a very reliable energy source."
        },
        {
            id:10,
            Q:"How does PV solar work?",
            A:"diagram"
        }
        
    ],
    section2:[
        {
            id:11,
            Q:"In a dilemma of choosing what’s best for you? Does enviNova Smartech  provide a site survey to overcome this?",
            A:"Yes. If you have doubts regarding which system is best for you, you are free to reach out to us at our customer care. Our executive will call and guide you regarding the same. However, if you’re still not satisfied, you can book a site survey free of cost.",
        },
        {
            id:12,
            Q:"How can you apply for subsidies? ",
            A:"The process has been simplified by us, one of our executives will collect all the required documents from you and will further submit them to a local authority to avail the subsidy. ",
        },
        {
            id:13,
            Q:"What are the kinds of financing and payment options available? ",
            A:"We charge a booking amount of ₹1000 and the remaining payment can be done after the installation process is complete. To pay for your solar plant, you can either pay online through debit/credit card, net banking, Paytm, UPI or opt for cash on delivery. However, if you like, you can choose the EMI option. If you choose to proceed to complete the process of EMI with our partnered bank you can avail No cost EMI at 0% interest rate. ",
        },
        {
            id:14,
            Q:"Do we offer cancellation after the order has been placed? ",
            A:"Yes, you can cancel your order or refuse to accept it at the time of delivery or before installation. If you cancel your order before delivery, we refund the full booking amount. If you cancel at time of delivery we deduct ₹100 as cancellation charges and  refund the  remaining ₹900 through net banking. However, if seal is broken and you change your mind before installation, we do not refund the booking amount of ₹1000.",
        },
        
        {
            id:15,
            Q:"How long does the entire process of installation take? ",
            A:"The installation process for the off-grid system takes up to 4 days from the date of booking to final set up. However, for the on-grid system it can take up to 15-30 days depending upon when the local electricity board grants an approval. Once approval is granted we deliver and install in next 3 working days. Be sure that there shall be no delays at our end.",
        },
        {
            id:16,
            Q:"Does pre-booking with full amount include some additional discounts? ",
            A:"No, we have a minimal booking amount of Rs1000. If you wish to pay full amount before hand, we do not offer any further discount. But we do have discount coupons storewide for the community and referral program.",
        },
        {
            id:17,
            Q:"Are there any add-on installation charges? ",
            A:"No there are no additional installation or hidden charges. We have one fixed price which includes everything.",
        },
        {
            id:18,
            Q:"What is the community and rewards program?",
            A:"We at enviNova Smartech are deeply concerned about our environment and aim at making people consciously aware about it too. For this we have initiated a community program for our customers. Once you purchase from us, you are eligible for our community program, a dedicated feature in our mobile app. In this we will upload weekly challenges, the theme of them being sustainability. On completing those challenges, you will win reward points and a cash back which you can redeem at our store section.",
        },

    ],

}
export default faqData;